kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.configmap.name }}-{{ .Release.Name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "back-end.labels" . | nindent 4 }}
data:
  RDS_CONNECTION_STRING: {{ .Values.configmap.RDS_CONNECTION_STRING }}
  RDS_DB_NAME: {{ .Values.configmap.RDS_DB_NAME }}
  S3_BUCKET_NAME: {{ .Values.configmap.S3_BUCKET_NAME }}
  REGION: {{ .Values.configmap.REGION }}
  REDIS_SENTINEL_HOSTNAME: {{ .Values.configmap.REDIS_SENTINEL_HOSTNAME }}
  REDIS_MASTERNAME: {{ .Values.configmap.REDIS_MASTERNAME }}
  REDIS_SENTINEL_PORT: {{ .Values.configmap.REDIS_SENTINEL_PORT | quote }}