kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.configmap.name }}-{{ .Release.Name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "front-end.labels" . | nindent 4 }}
data:
  REACT_APP_BACKENDURL: {{ .Values.configmap.backendIp}}