apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
    {{- include "front-end.labels" . | nindent 4 }}
  name: {{ .Release.Name }}-{{ template "front-end.serviceAccountName" . }}-role
  namespace: {{ .Values.namespace.name }}
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "watch", "list"]

