apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.regcred.name }}-{{ .Release.Name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "front-end.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ .Values.secret.regcred.dockerconfigjson }}
type: {{ .Values.secret.regcred.type }}