apiVersion: v1
kind: Service
metadata:
  name: {{ include "front-end.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "front-end.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    {{- include "front-end.selectorLabels" . | nindent 4 }}
